<?php

define("PATH_MAIN", __DIR__ . DIRECTORY_SEPARATOR);
define("PATH_CONFIG", __DIR__ . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR);
define("PATH_CONFIG_PRIVATE", PATH_CONFIG . DIRECTORY_SEPARATOR . 'private' . DIRECTORY_SEPARATOR);
define("PATH_CLASS", __DIR__ . DIRECTORY_SEPARATOR . 'class' . DIRECTORY_SEPARATOR);
define("PATH_VIEW", __DIR__ . DIRECTORY_SEPARATOR . 'view' . DIRECTORY_SEPARATOR);

